### ISSUE TITLE
Creating logstash container fails

### ISSUE THREAD

**Issue by ugogbos99** [amd/pensando-elk#15]
When installing ELK, I get this error during installation of logstash

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/logstash/pipelines.yml" to rootfs at "/usr/share/logstash/config/pipelines.yml": mount /logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by punisherVX** [comment]
Hi @ugogbos99 - 
Are you using sudo to run docker-compose?  Everything needs to be run as a normal user.  To allow the normal user to run docker, they will need to be part of the docker group for the OS.

What leads me to this conclusion is that the above error states it is trying to mount /logstash/pipelines.yml but there should be a base directory in front of that - as an example /home/user/pensando-elk/logstash/pipelines.yml or something similar.

**Comment by ugogbos99** [comment]
Hi @punisherVX 

Thanks for the assistance. That indeed was my challenge. Once I added my user to the docker group, I was able to successfully install ELK. Much appreciated.

**Comment by ugogbos99** [comment]
Hi @punisherVX

Thanks for the assistance. That indeed was my challenge. Once I added my user to the docker group, I was able to successfully install ELK. Much appreciated.
